# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    loaders:
        default:
            filesystem:
                data_root: "%kernel.root_dir%/../var"
    driver: "gd"
    resolvers:
        default:
            web_path:
                web_root: "%kernel.root_dir%/../public"
    filter_sets:
        #resize_table
        resize_table:
            quality: 80
            filters:
                relative_resize:
                    widen: 200
                    allow_upscale: true