vich_uploader:
    db_driver: orm

    mappings:
        restaurant_image:
            uri_prefix: /uploads/images
            upload_destination: '%kernel.project_dir%/var/uploads/images'
            namer:
                service: Vich\UploaderBundle\Naming\Base64Namer